# Generated by Django 2.1.5 on 2019-01-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
