# Generated by Django 2.1.5 on 2019-01-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190129_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurer',
            options={'ordering': ('name',), 'verbose_name': 'insurer'},
        ),
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ('name',), 'verbose_name': 'risk'},
        ),
        migrations.AlterModelOptions(
            name='riskfield',
            options={'ordering': ('name',), 'verbose_name': 'riskfield'},
        ),
    ]
