# Generated by Django 2.1.5 on 2019-01-30 22:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190129_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='coverage_amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_fields', to='api.Risk'),
        ),
    ]
